version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
       - echo "Pre build stage"
       - java -version
       - chmod +x ./gradlew
  build:
    commands:
       - echo "Build stage"
       - ./gradlew build
       - mv ./build/libs/*.jar ./
       - ls -al 
  # post_build:
  #   commands:
  #      - echo "Post build stage"
  #      - nohup java -jar -Dserver.port=$PORT ./build/libs/spring-boot-helloworld-0.0.1-SNAPSHOT.jar >/dev/null 2>&1 &
  #      - sleep 60
  #      - sh ./script/service_validate.sh   
  #      - sudo killall java
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - src-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - script/*
  discard-paths: yes

